OBJECTS = $(SOURCES_DIR)/search_engine.o \
			$(SOURCES_DIR)/crawler.o \
			$(SOURCES_DIR)/web_page.o \
			$(SOURCES_DIR)/json_file_reader.o \
			$(SOURCES_DIR)/curlpp_downloader.o \
			$(SOURCES_DIR)/gumbo_parser.o \
			$(SOURCES_DIR)/data_base.o \
			$(SOURCES_DIR)/update_data.o \
			$(SOURCES_DIR)/word_index.o \
			$(SOURCES_DIR)/link_data.o \
			$(SOURCES_DIR)/string_utils.o \
			$(SOURCES_DIR)/word_page.o \
			$(SOURCES_DIR)/validator.o \
			$(SOURCES_DIR)/search.o \
			$(SOURCES_DIR)/query.o \
			$(SOURCES_DIR)/ui.o \
			$(SOURCES_DIR)/crawler_mannager.o

-include ../makefile.common
