OBJECTS = $(SOURCES_DIR)/word_index.o \
        	$(SOURCES_DIR)/word_page.o \
         	$(SOURCES_DIR)/data_base.o \
        	$(SOURCES_DIR)/link_data.o \
			$(SOURCES_DIR)/string_utils.o

-include ../makefile.common
