OBJECTS = $(SOURCES_DIR)/search.o \
        	$(SOURCES_DIR)/query.o \
         	$(SOURCES_DIR)/ui.o \
        	$(SOURCES_DIR)/data_base.o \
			$(SOURCES_DIR)/word_index.o \
			$(SOURCES_DIR)/word_page.o \
			$(SOURCES_DIR)/string_utils.o \
			$(SOURCES_DIR)/link_data.o

-include ../makefile.common
